{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.policyBundleToken.name }}
  namespace: {{ include "neuromesh.namespace" . }}
type: Opaque
stringData:
  token: {{ .Values.secrets.policyBundleToken.token | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.policyBundleSigningKey.name }}
  namespace: {{ include "neuromesh.namespace" . }}
type: Opaque
stringData:
  signing.pem: |-
{{ .Values.secrets.policyBundleSigningKey.signingPem | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.policyBundlePubkey.name }}
  namespace: {{ include "neuromesh.namespace" . }}
type: Opaque
stringData:
  bundle.pub: |-
{{ .Values.secrets.policyBundlePubkey.bundlePub | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.spiffeTrustBundle.name }}
  namespace: {{ include "neuromesh.namespace" . }}
type: Opaque
stringData:
  bundle.pem: |-
{{ .Values.secrets.spiffeTrustBundle.bundlePem | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.cosignPubkey.name }}
  namespace: {{ include "neuromesh.namespace" . }}
type: Opaque
stringData:
  cosign.pub: |-
{{ .Values.secrets.cosignPubkey.cosignPub | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.admissionWebhookTls.name }}
  namespace: {{ include "neuromesh.namespace" . }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secrets.admissionWebhookTls.tlsCrt | quote }}
  tls.key: {{ .Values.secrets.admissionWebhookTls.tlsKey | quote }}
{{- end }}
